const googleCategories = [
{ '_id': "/Adult"},
{ '_id': "/Arts & Entertainment"},
{ '_id': "/Arts & Entertainment/Celebrities & Entertainment News"},
{ '_id': "/Arts & Entertainment/Comics & Animation"},
{ '_id': "/Arts & Entertainment/Comics & Animation/Anime & Manga"},
{ '_id': "/Arts & Entertainment/Comics & Animation/Cartoons"},
{ '_id': "/Arts & Entertainment/Comics & Animation/Comics"},
{ '_id': "/Arts & Entertainment/Entertainment Industry"},
{ '_id': "/Arts & Entertainment/Entertainment Industry/Film & TV Industry"},
{ '_id': "/Arts & Entertainment/Entertainment Industry/Recording Industry"},
{ '_id': "/Arts & Entertainment/Events & Listings"},
{ '_id': "/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife"},
{ '_id': "/Arts & Entertainment/Events & Listings/Concerts & Music Festivals"},
{ '_id': "/Arts & Entertainment/Events & Listings/Expos & Conventions"},
{ '_id': "/Arts & Entertainment/Events & Listings/Film Festivals"},
{ '_id': "/Arts & Entertainment/Events & Listings/Movie Listings & Theater Showtimes"},
{ '_id': "/Arts & Entertainment/Fun & Trivia"},
{ '_id': "/Arts & Entertainment/Fun & Trivia/Flash-Based Entertainment"},
{ '_id': "/Arts & Entertainment/Fun & Trivia/Fun Tests & Silly Surveys"},
{ '_id': "/Arts & Entertainment/Humor"},
{ '_id': "/Arts & Entertainment/Humor/Funny Pictures & Videos"},
{ '_id': "/Arts & Entertainment/Humor/Political Humor"},
{ '_id': "/Arts & Entertainment/Movies"},
{ '_id': "/Arts & Entertainment/Music & Audio"},
{ '_id': "/Arts & Entertainment/Music & Audio/CD & Audio Shopping"},
{ '_id': "/Arts & Entertainment/Music & Audio/Classical Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Country Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Dance & Electronic Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Experimental & Industrial Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Jazz & Blues"},
{ '_id': "/Arts & Entertainment/Music & Audio/Music Education & Instruction"},
{ '_id': "/Arts & Entertainment/Music & Audio/Music Equipment & Technology"},
{ '_id': "/Arts & Entertainment/Music & Audio/Music Reference"},
{ '_id': "/Arts & Entertainment/Music & Audio/Music Streams & Downloads"},
{ '_id': "/Arts & Entertainment/Music & Audio/Music Videos"},
{ '_id': "/Arts & Entertainment/Music & Audio/Pop Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Radio"},
{ '_id': "/Arts & Entertainment/Music & Audio/Religious Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Rock Music"},
{ '_id': "/Arts & Entertainment/Music & Audio/Soundtracks"},
{ '_id': "/Arts & Entertainment/Music & Audio/Urban & Hip-Hop"},
{ '_id': "/Arts & Entertainment/Music & Audio/World Music"},
{ '_id': "/Arts & Entertainment/Offbeat"},
{ '_id': "/Arts & Entertainment/Offbeat/Occult & Paranormal"},
{ '_id': "/Arts & Entertainment/Online Media"},
{ '_id': "/Arts & Entertainment/Online Media/Online Image Galleries"},
{ '_id': "/Arts & Entertainment/Performing Arts"},
{ '_id': "/Arts & Entertainment/Performing Arts/Acting & Theater"},
{ '_id': "/Arts & Entertainment/Performing Arts/Circus"},
{ '_id': "/Arts & Entertainment/Performing Arts/Dance"},
{ '_id': "/Arts & Entertainment/Performing Arts/Magic"},
{ '_id': "/Arts & Entertainment/Performing Arts/Opera"},
{ '_id': "/Arts & Entertainment/TV & Video"},
{ '_id': "/Arts & Entertainment/TV & Video/Online Video"},
{ '_id': "/Arts & Entertainment/TV & Video/TV Commercials"},
{ '_id': "/Arts & Entertainment/TV & Video/TV Shows & Programs"},
{ '_id': "/Arts & Entertainment/Visual Art & Design"},
{ '_id': "/Arts & Entertainment/Visual Art & Design/Architecture"},
{ '_id': "/Arts & Entertainment/Visual Art & Design/Art Museums & Galleries"},
{ '_id': "/Arts & Entertainment/Visual Art & Design/Design"},
{ '_id': "/Arts & Entertainment/Visual Art & Design/Painting"},
{ '_id': "/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts"},
{ '_id': "/Autos & Vehicles"},
{ '_id': "/Autos & Vehicles/Bicycles & Accessories"},
{ '_id': "/Autos & Vehicles/Bicycles & Accessories/BMX Bikes"},
{ '_id': "/Autos & Vehicles/Bicycles & Accessories/Bike Parts & Repair"},
{ '_id': "/Autos & Vehicles/Boats & Watercraft"},
{ '_id': "/Autos & Vehicles/Campers & RVs"},
{ '_id': "/Autos & Vehicles/Classic Vehicles"},
{ '_id': "/Autos & Vehicles/Commercial Vehicles/Cargo Trucks & Trailers"},
{ '_id': "/Autos & Vehicles/Motor Vehicles (By Type)"},
{ '_id': "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles"},
{ '_id': "/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles"},
{ '_id': "/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles"},
{ '_id': "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks & SUVs"},
{ '_id': "/Autos & Vehicles/Vehicle Codes & Driving Laws"},
{ '_id': "/Autos & Vehicles/Vehicle Codes & Driving Laws/Vehicle Licensing & Registration"},
{ '_id': "/Autos & Vehicles/Vehicle Parts & Services"},
{ '_id': "/Autos & Vehicles/Vehicle Parts & Services/Gas Prices & Vehicle Fueling"},
{ '_id': "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Parts & Accessories"},
{ '_id': "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Repair & Maintenance"},
{ '_id': "/Autos & Vehicles/Vehicle Shopping"},
{ '_id': "/Autos & Vehicles/Vehicle Shopping/Used Vehicles"},
{ '_id': "/Autos & Vehicles/Vehicle Shows"},
{ '_id': "/Beauty & Fitness"},
{ '_id': "/Beauty & Fitness/Beauty Pageants"},
{ '_id': "/Beauty & Fitness/Body Art"},
{ '_id': "/Beauty & Fitness/Cosmetic Procedures"},
{ '_id': "/Beauty & Fitness/Cosmetic Procedures/Cosmetic Surgery"},
{ '_id': "/Beauty & Fitness/Cosmetology & Beauty Professionals"},
{ '_id': "/Beauty & Fitness/Face & Body Care"},
{ '_id': "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries"},
{ '_id': "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics"},
{ '_id': "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances"},
{ '_id': "/Beauty & Fitness/Face & Body Care/Skin & Nail Care"},
{ '_id': "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal"},
{ '_id': "/Beauty & Fitness/Fashion & Style"},
{ '_id': "/Beauty & Fitness/Fashion & Style/Fashion Designers & Collections"},
{ '_id': "/Beauty & Fitness/Fitness"},
{ '_id': "/Beauty & Fitness/Hair Care"},
{ '_id': "/Beauty & Fitness/Hair Care/Hair Loss"},
{ '_id': "/Beauty & Fitness/Spas & Beauty Services"},
{ '_id': "/Beauty & Fitness/Spas & Beauty Services/Massage Therapy"},
{ '_id': "/Beauty & Fitness/Weight Loss"},
{ '_id': "/Books & Literature"},
{ '_id': "/Books & Literature/Children's Literature"},
{ '_id': "/Books & Literature/E-Books"},
{ '_id': "/Books & Literature/Fan Fiction"},
{ '_id': "/Books & Literature/Literary Classics"},
{ '_id': "/Books & Literature/Poetry"},
{ '_id': "/Books & Literature/Writers Resources"},
{ '_id': "/Business & Industrial"},
{ '_id': "/Business & Industrial/Advertising & Marketing/Public Relations"},
{ '_id': "/Business & Industrial/Aerospace & Defense/Space Technology"},
{ '_id': "/Business & Industrial/Agriculture & Forestry"},
{ '_id': "/Business & Industrial/Agriculture & Forestry/Agricultural Equipment"},
{ '_id': "/Business & Industrial/Agriculture & Forestry/Forestry"},
{ '_id': "/Business & Industrial/Agriculture & Forestry/Livestock"},
{ '_id': "/Business & Industrial/Automotive Industry"},
{ '_id': "/Business & Industrial/Business Education"},
{ '_id': "/Business & Industrial/Business Finance"},
{ '_id': "/Business & Industrial/Business Finance/Venture Capital"},
{ '_id': "/Business & Industrial/Business Operations"},
{ '_id': "/Business & Industrial/Business Operations/Business Plans & Presentations"},
{ '_id': "/Business & Industrial/Business Operations/Management"},
{ '_id': "/Business & Industrial/Business Services"},
{ '_id': "/Business & Industrial/Business Services/Consulting"},
{ '_id': "/Business & Industrial/Business Services/Corporate Events"},
{ '_id': "/Business & Industrial/Business Services/E-Commerce Services"},
{ '_id': "/Business & Industrial/Business Services/Fire & Security Services"},
{ '_id': "/Business & Industrial/Business Services/Office Services"},
{ '_id': "/Business & Industrial/Business Services/Office Supplies"},
{ '_id': "/Business & Industrial/Business Services/Writing & Editing Services"},
{ '_id': "/Business & Industrial/Chemicals Industry"},
{ '_id': "/Business & Industrial/Chemicals Industry/Cleaning Agents"},
{ '_id': "/Business & Industrial/Chemicals Industry/Plastics & Polymers"},
{ '_id': "/Business & Industrial/Construction & Maintenance"},
{ '_id': "/Business & Industrial/Construction & Maintenance/Building Materials & Supplies"},
{ '_id': "/Business & Industrial/Energy & Utilities"},
{ '_id': "/Business & Industrial/Energy & Utilities/Electricity"},
{ '_id': "/Business & Industrial/Energy & Utilities/Oil & Gas"},
{ '_id': "/Business & Industrial/Energy & Utilities/Renewable & Alternative Energy"},
{ '_id': "/Business & Industrial/Hospitality Industry"},
{ '_id': "/Business & Industrial/Hospitality Industry/Event Planning"},
{ '_id': "/Business & Industrial/Hospitality Industry/Food Service"},
{ '_id': "/Business & Industrial/Industrial Materials & Equipment"},
{ '_id': "/Business & Industrial/Industrial Materials & Equipment/Heavy Machinery"},
{ '_id': "/Business & Industrial/Manufacturing"},
{ '_id': "/Business & Industrial/Metals & Mining"},
{ '_id': "/Business & Industrial/Metals & Mining/Precious Metals"},
{ '_id': "/Business & Industrial/Pharmaceuticals & Biotech"},
{ '_id': "/Business & Industrial/Printing & Publishing"},
{ '_id': "/Business & Industrial/Retail Trade"},
{ '_id': "/Business & Industrial/Retail Trade/Retail Equipment & Technology"},
{ '_id': "/Business & Industrial/Small Business/MLM & Business Opportunities"},
{ '_id': "/Business & Industrial/Textiles & Nonwovens"},
{ '_id': "/Business & Industrial/Transportation & Logistics"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Freight & Trucking"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Mail & Package Delivery"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Maritime Transport"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Moving & Relocation"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Packaging"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Parking"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Rail Transport"},
{ '_id': "/Business & Industrial/Transportation & Logistics/Urban Transport"},
{ '_id': "/Computers & Electronics"},
{ '_id': "/Computers & Electronics/CAD & CAM"},
{ '_id': "/Computers & Electronics/Computer Hardware"},
{ '_id': "/Computers & Electronics/Computer Hardware/Computer Components"},
{ '_id': "/Computers & Electronics/Computer Hardware/Computer Drives & Storage"},
{ '_id': "/Computers & Electronics/Computer Hardware/Computer Peripherals"},
{ '_id': "/Computers & Electronics/Computer Hardware/Desktop Computers"},
{ '_id': "/Computers & Electronics/Computer Hardware/Laptops & Notebooks"},
{ '_id': "/Computers & Electronics/Computer Security"},
{ '_id': "/Computers & Electronics/Computer Security/Hacking & Cracking"},
{ '_id': "/Computers & Electronics/Consumer Electronics"},
{ '_id': "/Computers & Electronics/Consumer Electronics/Audio Equipment"},
{ '_id': "/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment"},
{ '_id': "/Computers & Electronics/Consumer Electronics/Car Electronics"},
{ '_id': "/Computers & Electronics/Consumer Electronics/Drones & RC Aircraft"},
{ '_id': "/Computers & Electronics/Consumer Electronics/GPS & Navigation"},
{ '_id': "/Computers & Electronics/Consumer Electronics/Game Systems & Consoles"},
{ '_id': "/Computers & Electronics/Consumer Electronics/TV & Video Equipment"},
{ '_id': "/Computers & Electronics/Electronics & Electrical"},
{ '_id': "/Computers & Electronics/Electronics & Electrical/Electronic Components"},
{ '_id': "/Computers & Electronics/Electronics & Electrical/Power Supplies"},
{ '_id': "/Computers & Electronics/Enterprise Technology"},
{ '_id': "/Computers & Electronics/Enterprise Technology/Data Management"},
{ '_id': "/Computers & Electronics/Networking"},
{ '_id': "/Computers & Electronics/Networking/Data Formats & Protocols"},
{ '_id': "/Computers & Electronics/Networking/Network Monitoring & Management"},
{ '_id': "/Computers & Electronics/Networking/VPN & Remote Access"},
{ '_id': "/Computers & Electronics/Programming"},
{ '_id': "/Computers & Electronics/Programming/Java (Programming Language)"},
{ '_id': "/Computers & Electronics/Software"},
{ '_id': "/Computers & Electronics/Software/Business & Productivity Software"},
{ '_id': "/Computers & Electronics/Software/Device Drivers"},
{ '_id': "/Computers & Electronics/Software/Internet Software"},
{ '_id': "/Computers & Electronics/Software/Multimedia Software"},
{ '_id': "/Computers & Electronics/Software/Operating Systems"},
{ '_id': "/Computers & Electronics/Software/Software Utilities"},
{ '_id': "/Finance"},
{ '_id': "/Finance/Accounting & Auditing"},
{ '_id': "/Finance/Accounting & Auditing/Billing & Invoicing"},
{ '_id': "/Finance/Accounting & Auditing/Tax Preparation & Planning"},
{ '_id': "/Finance/Banking"},
{ '_id': "/Finance/Credit & Lending"},
{ '_id': "/Finance/Credit & Lending/Credit Cards"},
{ '_id': "/Finance/Credit & Lending/Credit Reporting & Monitoring"},
{ '_id': "/Finance/Credit & Lending/Loans"},
{ '_id': "/Finance/Financial Planning & Management"},
{ '_id': "/Finance/Financial Planning & Management/Retirement & Pension"},
{ '_id': "/Finance/Grants, Scholarships & Financial Aid"},
{ '_id': "/Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships"},
{ '_id': "/Finance/Insurance"},
{ '_id': "/Finance/Insurance/Health Insurance"},
{ '_id': "/Finance/Investing"},
{ '_id': "/Finance/Investing/Commodities & Futures Trading"},
{ '_id': "/Finance/Investing/Currencies & Foreign Exchange"},
{ '_id': "/Finance/Investing/Stocks & Bonds"},
{ '_id': "/Food & Drink"},
{ '_id': "/Food & Drink/Beverages"},
{ '_id': "/Food & Drink/Beverages/Alcoholic Beverages"},
{ '_id': "/Food & Drink/Beverages/Coffee & Tea"},
{ '_id': "/Food & Drink/Beverages/Juice"},
{ '_id': "/Food & Drink/Beverages/Soft Drinks"},
{ '_id': "/Food & Drink/Cooking & Recipes"},
{ '_id': "/Food & Drink/Cooking & Recipes/BBQ & Grilling"},
{ '_id': "/Food & Drink/Cooking & Recipes/Desserts"},
{ '_id': "/Food & Drink/Cooking & Recipes/Soups & Stews"},
{ '_id': "/Food & Drink/Food"},
{ '_id': "/Food & Drink/Food & Grocery Retailers"},
{ '_id': "/Food & Drink/Food/Baked Goods"},
{ '_id': "/Food & Drink/Food/Breakfast Foods"},
{ '_id': "/Food & Drink/Food/Candy & Sweets"},
{ '_id': "/Food & Drink/Food/Grains & Pasta"},
{ '_id': "/Food & Drink/Food/Meat & Seafood"},
{ '_id': "/Food & Drink/Food/Snack Foods"},
{ '_id': "/Food & Drink/Restaurants"},
{ '_id': "/Food & Drink/Restaurants/Fast Food"},
{ '_id': "/Food & Drink/Restaurants/Pizzerias"},
{ '_id': "/Food & Drink/Restaurants/Restaurant Reviews & Reservations"},
{ '_id': "/Games"},
{ '_id': "/Games/Arcade & Coin-Op Games"},
{ '_id': "/Games/Board Games"},
{ '_id': "/Games/Board Games/Chess & Abstract Strategy Games"},
{ '_id': "/Games/Board Games/Miniatures & Wargaming"},
{ '_id': "/Games/Card Games"},
{ '_id': "/Games/Card Games/Collectible Card Games"},
{ '_id': "/Games/Card Games/Poker & Casino Games"},
{ '_id': "/Games/Computer & Video Games"},
{ '_id': "/Games/Computer & Video Games/Casual Games"},
{ '_id': "/Games/Computer & Video Games/Driving & Racing Games"},
{ '_id': "/Games/Computer & Video Games/Fighting Games"},
{ '_id': "/Games/Computer & Video Games/Music & Dance Games"},
{ '_id': "/Games/Computer & Video Games/Sandbox Games"},
{ '_id': "/Games/Computer & Video Games/Shooter Games"},
{ '_id': "/Games/Computer & Video Games/Simulation Games"},
{ '_id': "/Games/Computer & Video Games/Sports Games"},
{ '_id': "/Games/Computer & Video Games/Strategy Games"},
{ '_id': "/Games/Computer & Video Games/Video Game Emulation"},
{ '_id': "/Games/Family-Oriented Games & Activities"},
{ '_id': "/Games/Family-Oriented Games & Activities/Drawing & Coloring"},
{ '_id': "/Games/Family-Oriented Games & Activities/Dress-Up & Fashion Games"},
{ '_id': "/Games/Gambling"},
{ '_id': "/Games/Gambling/Lottery"},
{ '_id': "/Games/Online Games/Massively Multiplayer Games"},
{ '_id': "/Games/Puzzles & Brainteasers"},
{ '_id': "/Games/Roleplaying Games"},
{ '_id': "/Games/Table Games"},
{ '_id': "/Games/Table Games/Billiards"},
{ '_id': "/Games/Word Games"},
{ '_id': "/Health"},
{ '_id': "/Health/Aging & Geriatrics"},
{ '_id': "/Health/Health Conditions"},
{ '_id': "/Health/Health Conditions/AIDS & HIV"},
{ '_id': "/Health/Health Conditions/Allergies"},
{ '_id': "/Health/Health Conditions/Arthritis"},
{ '_id': "/Health/Health Conditions/Cancer"},
{ '_id': "/Health/Health Conditions/Diabetes"},
{ '_id': "/Health/Health Conditions/Ear Nose & Throat"},
{ '_id': "/Health/Health Conditions/Eating Disorders"},
{ '_id': "/Health/Health Conditions/Endocrine Conditions"},
{ '_id': "/Health/Health Conditions/Genetic Disorders"},
{ '_id': "/Health/Health Conditions/Heart & Hypertension"},
{ '_id': "/Health/Health Conditions/Infectious Diseases"},
{ '_id': "/Health/Health Conditions/Neurological Conditions"},
{ '_id': "/Health/Health Conditions/Obesity"},
{ '_id': "/Health/Health Conditions/Pain Management"},
{ '_id': "/Health/Health Conditions/Respiratory Conditions"},
{ '_id': "/Health/Health Conditions/Skin Conditions"},
{ '_id': "/Health/Health Conditions/Sleep Disorders"},
{ '_id': "/Health/Health Education & Medical Training"},
{ '_id': "/Health/Health Foundations & Medical Research"},
{ '_id': "/Health/Medical Devices & Equipment"},
{ '_id': "/Health/Medical Facilities & Services"},
{ '_id': "/Health/Medical Facilities & Services/Doctors' Offices"},
{ '_id': "/Health/Medical Facilities & Services/Hospitals & Treatment Centers"},
{ '_id': "/Health/Medical Facilities & Services/Medical Procedures"},
{ '_id': "/Health/Medical Facilities & Services/Physical Therapy"},
{ '_id': "/Health/Men's Health"},
{ '_id': "/Health/Mental Health"},
{ '_id': "/Health/Mental Health/Anxiety & Stress"},
{ '_id': "/Health/Mental Health/Depression"},
{ '_id': "/Health/Nursing"},
{ '_id': "/Health/Nursing/Assisted Living & Long Term Care"},
{ '_id': "/Health/Nutrition"},
{ '_id': "/Health/Nutrition/Special & Restricted Diets"},
{ '_id': "/Health/Nutrition/Vitamins & Supplements"},
{ '_id': "/Health/Oral & Dental Care"},
{ '_id': "/Health/Pharmacy"},
{ '_id': "/Health/Pharmacy/Drugs & Medications"},
{ '_id': "/Health/Public Health"},
{ '_id': "/Health/Public Health/Occupational Health & Safety"},
{ '_id': "/Health/Reproductive Health"},
{ '_id': "/Health/Substance Abuse"},
{ '_id': "/Health/Substance Abuse/Drug & Alcohol Testing"},
{ '_id': "/Health/Substance Abuse/Drug & Alcohol Treatment"},
{ '_id': "/Health/Substance Abuse/Smoking & Smoking Cessation"},
{ '_id': "/Health/Substance Abuse/Steroids & Performance-Enhancing Drugs"},
{ '_id': "/Health/Vision Care"},
{ '_id': "/Health/Vision Care/Eyeglasses & Contacts"},
{ '_id': "/Health/Women's Health"},
{ '_id': "/Hobbies & Leisure"},
{ '_id': "/Hobbies & Leisure/Clubs & Organizations"},
{ '_id': "/Hobbies & Leisure/Clubs & Organizations/Youth Organizations & Resources"},
{ '_id': "/Hobbies & Leisure/Crafts"},
{ '_id': "/Hobbies & Leisure/Crafts/Fiber & Textile Arts"},
{ '_id': "/Hobbies & Leisure/Merit Prizes & Contests"},
{ '_id': "/Hobbies & Leisure/Outdoors"},
{ '_id': "/Hobbies & Leisure/Outdoors/Fishing"},
{ '_id': "/Hobbies & Leisure/Outdoors/Hiking & Camping"},
{ '_id': "/Hobbies & Leisure/Paintball"},
{ '_id': "/Hobbies & Leisure/Radio Control & Modeling"},
{ '_id': "/Hobbies & Leisure/Radio Control & Modeling/Model Trains & Railroads"},
{ '_id': "/Hobbies & Leisure/Special Occasions"},
{ '_id': "/Hobbies & Leisure/Special Occasions/Holidays & Seasonal Events"},
{ '_id': "/Hobbies & Leisure/Special Occasions/Weddings"},
{ '_id': "/Hobbies & Leisure/Water Activities"},
{ '_id': "/Hobbies & Leisure/Water Activities/Boating"},
{ '_id': "/Hobbies & Leisure/Water Activities/Surf & Swim"},
{ '_id': "/Home & Garden"},
{ '_id': "/Home & Garden/Bed & Bath"},
{ '_id': "/Home & Garden/Bed & Bath/Bathroom"},
{ '_id': "/Home & Garden/Domestic Services"},
{ '_id': "/Home & Garden/Domestic Services/Cleaning Services"},
{ '_id': "/Home & Garden/Gardening & Landscaping"},
{ '_id': "/Home & Garden/HVAC & Climate Control"},
{ '_id': "/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves"},
{ '_id': "/Home & Garden/Home & Interior Decor"},
{ '_id': "/Home & Garden/Home Appliances"},
{ '_id': "/Home & Garden/Home Furnishings"},
{ '_id': "/Home & Garden/Home Furnishings/Curtains & Window Treatments"},
{ '_id': "/Home & Garden/Home Furnishings/Kitchen & Dining Furniture"},
{ '_id': "/Home & Garden/Home Furnishings/Lamps & Lighting"},
{ '_id': "/Home & Garden/Home Furnishings/Living Room Furniture"},
{ '_id': "/Home & Garden/Home Furnishings/Rugs & Carpets"},
{ '_id': "/Home & Garden/Home Improvement"},
{ '_id': "/Home & Garden/Home Improvement/Construction & Power Tools"},
{ '_id': "/Home & Garden/Home Improvement/Doors & Windows"},
{ '_id': "/Home & Garden/Home Improvement/Flooring"},
{ '_id': "/Home & Garden/Home Improvement/House Painting & Finishing"},
{ '_id': "/Home & Garden/Home Improvement/Plumbing"},
{ '_id': "/Home & Garden/Home Safety & Security"},
{ '_id': "/Home & Garden/Home Storage & Shelving"},
{ '_id': "/Home & Garden/Home Swimming Pools, Saunas & Spas"},
{ '_id': "/Home & Garden/Kitchen & Dining"},
{ '_id': "/Home & Garden/Kitchen & Dining/Cookware & Diningware"},
{ '_id': "/Home & Garden/Kitchen & Dining/Major Kitchen Appliances"},
{ '_id': "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances"},
{ '_id': "/Home & Garden/Laundry"},
{ '_id': "/Home & Garden/Laundry/Washers & Dryers"},
{ '_id': "/Home & Garden/Nursery & Playroom"},
{ '_id': "/Home & Garden/Pest Control"},
{ '_id': "/Home & Garden/Yard & Patio"},
{ '_id': "/Home & Garden/Yard & Patio/Lawn Mowers"},
{ '_id': "/Internet & Telecom"},
{ '_id': "/Internet & Telecom/Communications Equipment"},
{ '_id': "/Internet & Telecom/Communications Equipment/Radio Equipment"},
{ '_id': "/Internet & Telecom/Email & Messaging"},
{ '_id': "/Internet & Telecom/Email & Messaging/Text & Instant Messaging"},
{ '_id': "/Internet & Telecom/Email & Messaging/Voice & Video Chat"},
{ '_id': "/Internet & Telecom/Mobile & Wireless"},
{ '_id': "/Internet & Telecom/Mobile & Wireless/Mobile & Wireless Accessories"},
{ '_id': "/Internet & Telecom/Mobile & Wireless/Mobile Apps & Add-Ons"},
{ '_id': "/Internet & Telecom/Mobile & Wireless/Mobile Phones"},
{ '_id': "/Internet & Telecom/Service Providers"},
{ '_id': "/Internet & Telecom/Service Providers/Cable & Satellite Providers"},
{ '_id': "/Internet & Telecom/Web Services"},
{ '_id': "/Internet & Telecom/Web Services/Affiliate Programs"},
{ '_id': "/Internet & Telecom/Web Services/Web Design & Development"},
{ '_id': "/Jobs & Education"},
{ '_id': "/Jobs & Education/Education"},
{ '_id': "/Jobs & Education/Education/Colleges & Universities"},
{ '_id': "/Jobs & Education/Education/Distance Learning"},
{ '_id': "/Jobs & Education/Education/Homeschooling"},
{ '_id': "/Jobs & Education/Education/Primary & Secondary Schooling (K-12)"},
{ '_id': "/Jobs & Education/Education/Standardized & Admissions Tests"},
{ '_id': "/Jobs & Education/Education/Teaching & Classroom Resources"},
{ '_id': "/Jobs & Education/Education/Training & Certification"},
{ '_id': "/Jobs & Education/Education/Vocational & Continuing Education"},
{ '_id': "/Jobs & Education/Jobs"},
{ '_id': "/Jobs & Education/Jobs/Career Resources & Planning"},
{ '_id': "/Jobs & Education/Jobs/Job Listings"},
{ '_id': "/Jobs & Education/Jobs/Resumes & Portfolios"},
{ '_id': "/Law & Government"},
{ '_id': "/Law & Government/Government"},
{ '_id': "/Law & Government/Government/Courts & Judiciary"},
{ '_id': "/Law & Government/Government/Visa & Immigration"},
{ '_id': "/Law & Government/Legal"},
{ '_id': "/Law & Government/Legal/Bankruptcy"},
{ '_id': "/Law & Government/Legal/Legal Education"},
{ '_id': "/Law & Government/Legal/Legal Services"},
{ '_id': "/Law & Government/Military"},
{ '_id': "/Law & Government/Public Safety"},
{ '_id': "/Law & Government/Public Safety/Crime & Justice"},
{ '_id': "/Law & Government/Public Safety/Emergency Services"},
{ '_id': "/Law & Government/Public Safety/Law Enforcement"},
{ '_id': "/Law & Government/Public Safety/Security Products & Services"},
{ '_id': "/Law & Government/Social Services"},
{ '_id': "/News"},
{ '_id': "/News/Business News"},
{ '_id': "/News/Business News/Company News"},
{ '_id': "/News/Business News/Financial Markets News"},
{ '_id': "/News/Gossip & Tabloid News/Scandals & Investigations"},
{ '_id': "/News/Health News"},
{ '_id': "/News/Politics"},
{ '_id': "/News/Sports News"},
{ '_id': "/News/Weather"},
{ '_id': "/Online Communities"},
{ '_id': "/Online Communities/Blogging Resources & Services"},
{ '_id': "/Online Communities/Dating & Personals"},
{ '_id': "/Online Communities/Dating & Personals/Matrimonial Services"},
{ '_id': "/Online Communities/Dating & Personals/Personals"},
{ '_id': "/Online Communities/Dating & Personals/Photo Rating Sites"},
{ '_id': "/Online Communities/File Sharing & Hosting"},
{ '_id': "/Online Communities/Online Goodies"},
{ '_id': "/Online Communities/Online Goodies/Clip Art & Animated GIFs"},
{ '_id': "/Online Communities/Online Goodies/Skins, Themes & Wallpapers"},
{ '_id': "/Online Communities/Online Goodies/Social Network Apps & Add-Ons"},
{ '_id': "/Online Communities/Photo & Video Sharing"},
{ '_id': "/Online Communities/Photo & Video Sharing/Photo & Image Sharing"},
{ '_id': "/Online Communities/Social Networks"},
{ '_id': "/Online Communities/Virtual Worlds"},
{ '_id': "/People & Society"},
{ '_id': "/People & Society/Family & Relationships"},
{ '_id': "/People & Society/Family & Relationships/Family"},
{ '_id': "/People & Society/Family & Relationships/Marriage"},
{ '_id': "/People & Society/Family & Relationships/Troubled Relationships"},
{ '_id': "/People & Society/Kids & Teens"},
{ '_id': "/People & Society/Kids & Teens/Children's Interests"},
{ '_id': "/People & Society/Kids & Teens/Teen Interests"},
{ '_id': "/People & Society/Religion & Belief"},
{ '_id': "/People & Society/Seniors & Retirement"},
{ '_id': "/People & Society/Social Issues & Advocacy"},
{ '_id': "/People & Society/Social Issues & Advocacy/Charity & Philanthropy"},
{ '_id': "/People & Society/Social Issues & Advocacy/Discrimination & Identity Relations"},
{ '_id': "/People & Society/Social Issues & Advocacy/Green Living & Environmental Issues"},
{ '_id': "/People & Society/Social Issues & Advocacy/Human Rights & Liberties"},
{ '_id': "/People & Society/Social Issues & Advocacy/Poverty & Hunger"},
{ '_id': "/People & Society/Social Issues & Advocacy/Work & Labor Issues"},
{ '_id': "/People & Society/Social Sciences"},
{ '_id': "/People & Society/Social Sciences/Economics"},
{ '_id': "/People & Society/Social Sciences/Political Science"},
{ '_id': "/People & Society/Social Sciences/Psychology"},
{ '_id': "/People & Society/Subcultures & Niche Interests"},
{ '_id': "/Pets & Animals"},
{ '_id': "/Pets & Animals/Animal Products & Services/Pet Food & Supplies"},
{ '_id': "/Pets & Animals/Animal Products & Services/Veterinarians"},
{ '_id': "/Pets & Animals/Pets"},
{ '_id': "/Pets & Animals/Pets/Birds"},
{ '_id': "/Pets & Animals/Pets/Cats"},
{ '_id': "/Pets & Animals/Pets/Dogs"},
{ '_id': "/Pets & Animals/Pets/Exotic Pets"},
{ '_id': "/Pets & Animals/Pets/Fish & Aquaria"},
{ '_id': "/Pets & Animals/Pets/Horses"},
{ '_id': "/Pets & Animals/Pets/Rabbits & Rodents"},
{ '_id': "/Pets & Animals/Pets/Reptiles & Amphibians"},
{ '_id': "/Pets & Animals/Wildlife"},
{ '_id': "/Real Estate"},
{ '_id': "/Real Estate/Real Estate Listings"},
{ '_id': "/Real Estate/Real Estate Listings/Bank-Owned & Foreclosed Properties"},
{ '_id': "/Real Estate/Real Estate Listings/Commercial Properties"},
{ '_id': "/Real Estate/Real Estate Listings/Lots & Land"},
{ '_id': "/Real Estate/Real Estate Listings/Residential Rentals"},
{ '_id': "/Real Estate/Real Estate Listings/Residential Sales"},
{ '_id': "/Real Estate/Real Estate Listings/Timeshares & Vacation Properties"},
{ '_id': "/Real Estate/Real Estate Services"},
{ '_id': "/Reference"},
{ '_id': "/Reference/Directories & Listings"},
{ '_id': "/Reference/Directories & Listings/Business & Personal Listings"},
{ '_id': "/Reference/General Reference"},
{ '_id': "/Reference/General Reference/Biographies & Quotations"},
{ '_id': "/Reference/General Reference/Calculators & Reference Tools"},
{ '_id': "/Reference/General Reference/Dictionaries & Encyclopedias"},
{ '_id': "/Reference/General Reference/Forms Guides & Templates"},
{ '_id': "/Reference/General Reference/Public Records"},
{ '_id': "/Reference/General Reference/Time & Calendars"},
{ '_id': "/Reference/Geographic Reference"},
{ '_id': "/Reference/Geographic Reference/Maps"},
{ '_id': "/Reference/Humanities"},
{ '_id': "/Reference/Humanities/History"},
{ '_id': "/Reference/Humanities/Myth & Folklore"},
{ '_id': "/Reference/Humanities/Philosophy"},
{ '_id': "/Reference/Language Resources"},
{ '_id': "/Reference/Language Resources/Foreign Language Resources"},
{ '_id': "/Reference/Libraries & Museums"},
{ '_id': "/Reference/Libraries & Museums/Museums"},
{ '_id': "/Science"},
{ '_id': "/Science/Astronomy"},
{ '_id': "/Science/Biological Sciences"},
{ '_id': "/Science/Biological Sciences/Neuroscience"},
{ '_id': "/Science/Chemistry"},
{ '_id': "/Science/Computer Science"},
{ '_id': "/Science/Earth Sciences"},
{ '_id': "/Science/Earth Sciences/Atmospheric Science"},
{ '_id': "/Science/Earth Sciences/Geology"},
{ '_id': "/Science/Ecology & Environment"},
{ '_id': "/Science/Ecology & Environment/Climate Change & Global Warming"},
{ '_id': "/Science/Engineering & Technology"},
{ '_id': "/Science/Engineering & Technology/Robotics"},
{ '_id': "/Science/Mathematics"},
{ '_id': "/Science/Mathematics/Statistics"},
{ '_id': "/Science/Physics"},
{ '_id': "/Science/Scientific Institutions"},
{ '_id': "/Sensitive Subjects"},
{ '_id': "/Shopping"},
{ '_id': "/Shopping/Antiques & Collectibles"},
{ '_id': "/Shopping/Apparel"},
{ '_id': "/Shopping/Apparel/Athletic Apparel"},
{ '_id': "/Shopping/Apparel/Casual Apparel"},
{ '_id': "/Shopping/Apparel/Children's Clothing"},
{ '_id': "/Shopping/Apparel/Clothing Accessories"},
{ '_id': "/Shopping/Apparel/Costumes"},
{ '_id': "/Shopping/Apparel/Eyewear"},
{ '_id': "/Shopping/Apparel/Footwear"},
{ '_id': "/Shopping/Apparel/Formal Wear"},
{ '_id': "/Shopping/Apparel/Headwear"},
{ '_id': "/Shopping/Apparel/Men's Clothing"},
{ '_id': "/Shopping/Apparel/Swimwear"},
{ '_id': "/Shopping/Apparel/Undergarments"},
{ '_id': "/Shopping/Apparel/Women's Clothing"},
{ '_id': "/Shopping/Auctions"},
{ '_id': "/Shopping/Classifieds"},
{ '_id': "/Shopping/Consumer Resources"},
{ '_id': "/Shopping/Consumer Resources/Consumer Advocacy & Protection"},
{ '_id': "/Shopping/Consumer Resources/Coupons & Discount Offers"},
{ '_id': "/Shopping/Consumer Resources/Product Reviews & Price Comparisons"},
{ '_id': "/Shopping/Entertainment Media"},
{ '_id': "/Shopping/Entertainment Media/Entertainment Media Rentals"},
{ '_id': "/Shopping/Gifts & Special Event Items"},
{ '_id': "/Shopping/Gifts & Special Event Items/Cards & Greetings"},
{ '_id': "/Shopping/Gifts & Special Event Items/Flowers"},
{ '_id': "/Shopping/Gifts & Special Event Items/Gifts"},
{ '_id': "/Shopping/Luxury Goods"},
{ '_id': "/Shopping/Mass Merchants & Department Stores"},
{ '_id': "/Shopping/Photo & Video Services"},
{ '_id': "/Shopping/Tobacco Products"},
{ '_id': "/Shopping/Toys"},
{ '_id': "/Shopping/Toys/Building Toys"},
{ '_id': "/Shopping/Toys/Die-cast & Toy Vehicles"},
{ '_id': "/Shopping/Toys/Dolls & Accessories"},
{ '_id': "/Shopping/Toys/Ride-On Toys & Wagons"},
{ '_id': "/Shopping/Toys/Stuffed Toys"},
{ '_id': "/Sports"},
{ '_id': "/Sports/Animal Sports"},
{ '_id': "/Sports/College Sports"},
{ '_id': "/Sports/Combat Sports"},
{ '_id': "/Sports/Combat Sports/Boxing"},
{ '_id': "/Sports/Combat Sports/Martial Arts"},
{ '_id': "/Sports/Combat Sports/Wrestling"},
{ '_id': "/Sports/Extreme Sports"},
{ '_id': "/Sports/Extreme Sports/Drag & Street Racing"},
{ '_id': "/Sports/Fantasy Sports"},
{ '_id': "/Sports/Individual Sports"},
{ '_id': "/Sports/Individual Sports/Cycling"},
{ '_id': "/Sports/Individual Sports/Golf"},
{ '_id': "/Sports/Individual Sports/Gymnastics"},
{ '_id': "/Sports/Individual Sports/Racquet Sports"},
{ '_id': "/Sports/Individual Sports/Skate Sports"},
{ '_id': "/Sports/Individual Sports/Track & Field"},
{ '_id': "/Sports/International Sports Competitions"},
{ '_id': "/Sports/International Sports Competitions/Olympics"},
{ '_id': "/Sports/Motor Sports"},
{ '_id': "/Sports/Sporting Goods"},
{ '_id': "/Sports/Sporting Goods/Sports Memorabilia"},
{ '_id': "/Sports/Sporting Goods/Winter Sports Equipment"},
{ '_id': "/Sports/Sports Coaching & Training"},
{ '_id': "/Sports/Team Sports"},
{ '_id': "/Sports/Team Sports/American Football"},
{ '_id': "/Sports/Team Sports/Australian Football"},
{ '_id': "/Sports/Team Sports/Baseball"},
{ '_id': "/Sports/Team Sports/Basketball"},
{ '_id': "/Sports/Team Sports/Cheerleading"},
{ '_id': "/Sports/Team Sports/Cricket"},
{ '_id': "/Sports/Team Sports/Hockey"},
{ '_id': "/Sports/Team Sports/Rugby"},
{ '_id': "/Sports/Team Sports/Soccer"},
{ '_id': "/Sports/Team Sports/Volleyball"},
{ '_id': "/Sports/Water Sports"},
{ '_id': "/Sports/Water Sports/Surfing"},
{ '_id': "/Sports/Water Sports/Swimming"},
{ '_id': "/Sports/Winter Sports"},
{ '_id': "/Sports/Winter Sports/Ice Skating"},
{ '_id': "/Sports/Winter Sports/Skiing & Snowboarding"},
{ '_id': "/Travel"},
{ '_id': "/Travel/Air Travel"},
{ '_id': "/Travel/Air Travel/Airport Parking & Transportation"},
{ '_id': "/Travel/Bus & Rail"},
{ '_id': "/Travel/Car Rental & Taxi Services"},
{ '_id': "/Travel/Cruises & Charters"},
{ '_id': "/Travel/Hotels & Accommodations"},
{ '_id': "/Travel/Hotels & Accommodations/Vacation Rentals & Short-Term Stays"},
{ '_id': "/Travel/Specialty Travel"},
{ '_id': "/Travel/Tourist Destinations"},
{ '_id': "/Travel/Tourist Destinations/Beaches & Islands"},
{ '_id': "/Travel/Tourist Destinations/Mountain & Ski Resorts"},
{ '_id': "/Travel/Tourist Destinations/Regional Parks & Gardens"},
{ '_id': "/Travel/Tourist Destinations/Theme Parks"},
{ '_id': "/Travel/Tourist Destinations/Zoos-Aquariums-Preserves"},
]

module.exports = { GoogleVisionCategories: googleCategories}